console.log((4+9+6)/77);
//var a= 10;
a =12;
// const a =9;

// console.log(a);
// let b = 7*a;
// console.log(b);
// const max =57;
// const actual=max-13;
// const percentage = actual/max;
// console.log(percentage);
let str = 'Hello,';
let str1 ="World";
console.log(`String Length : -`)
console.log (`${str} ${str1}`); 
console.log(str.length);
console.log(`String charAt`);
let str3 ="Aba jaba daba khaba (rabba";
console.log(str3.charAt(4))
console.log(`String indexOf and lastIndexOf`);
let str4 ="The code is undefined code code !";
console.log(str4.indexOf("c" , 4));
console.log(str4.lastIndexOf("c", 24));
console.log(str4.indexOf(""));
console.log(str4.lastIndexOf(""));
console.log(str4.length);
console.log("String slice and substring");
let str5 ="The morning is upon us!";
console.log(str5.length);
console.log(str5.slice(4,6));
console.log(str5.substring(24,1));
console.log(str5.slice(8,-4));
console.log(str5.substring(8,-4));
console.log("String split");
console.log(str5.split());
console.log(str5.split(""));
console.log(str5.split(" "));
console.log(str5.split("o"));
console.log(str5.split("upon",2));
console.log("Learning string include method");
let str6 ="The quick brown fox jumps over the dog";
console.log(str6.includes("fox"));
console.log(str6.includes("fox", 16));
console.log("Learning startWith and endWidth String methods");
console.log(str6.startsWith("The"));
console.log(str6.startsWith("The", 5));
console.log(str6.startsWith("The", 0));
console.log(str6.length);
console.log(str6.endsWith("dog",36));
console.log("String Concat");
console.log(str6.concat(", ", str5));
console.log("String method repeat()");
let str7 = "abc";
console.log(str7.repeat(3));
// console.log(str7.repeat(-1));
console.log("Learning trim(), trimStart(), trimEnd() methods of Strings");
let str8 = "    Hello Amulya     ";
let greetings = str8.trim();
console.log (str8)
console.log(greetings);
let TrimStart = str8.trimStart();
console.log(TrimStart);
let TrimEnd = str8.trimEnd();
console.log(TrimEnd);